### ISSUE TITLE
タグを使ったクロス フィルタリング

### ISSUE THREAD

**Issue by knmaki** [hanaseleb/Qiita-Power-BI-Report#1]
テンプレートを使って、さっそく自分の記事を分析してみました。アクセストークンだけでお手軽に導入できてよかったです。

タグを使ったクロス フィルタリングができればもっと便利なので、提案させてください。

# こんなふうにしたい
クロス フィルター前
![image](https://github.com/hanaseleb/Qiita-Power-BI-Report/assets/58804016/cc37b91b-56bc-4637-9f63-9c56e5820486)

クロス フィルター後
![image](https://github.com/hanaseleb/Qiita-Power-BI-Report/assets/58804016/6a599b39-5ff5-4c18-ab96-76ff292328ce)

# データ モデリング
`ItemTag`ブリッジ テーブルを用意します。
![image](https://github.com/hanaseleb/Qiita-Power-BI-Report/assets/58804016/7e6e7fb3-1e12-4716-abc0-e801afc622b0)

このテーブルと`Item`テーブルと`Tag`テーブル間で次のようにリレーションシップを設定します。
![image](https://github.com/hanaseleb/Qiita-Power-BI-Report/assets/58804016/86c3f68a-d159-46e6-89d6-ea538427001e)

あとは、右上のタグ別のビジュアルのメジャーを`Item[いいね数]`メジャー等に変更すればOK。

# 参考
今回、初めてファクトレス ファクト テーブルと双方向リレーションシップを使ってみました。
https://learn.microsoft.com/ja-jp/power-bi/guidance/relationships-many-to-many#relate-many-to-many-dimensions

**Comment by hanaseleb** [comment]
ご提案ありがとうございます！早速、とりいれ、1.1をリリースしてみました！ありがとうございます～！
